### ISSUE TITLE
PTAM Drone Camera Feed 

### ISSUE THREAD

**Issue by pulver22** [thinclab/uga_tum_ardrone#1]
Hi,

I'm using this package with tum_simulator.

After typing `roslaunch uga_tum_ardrone uga_tum_ardrone` the windows called "PTAM Drone Camera Feed", which should show the the tracking map, does not appear. In the console I don't have any error (or warning).

I was wondering if this functionality works only with a physical platform or I should be able to see it also in my case.

**Comment by kbogert** [comment]
Hi,

I just tested this and it worked perfectly.  A couple of questions:
1.  How are you launching tum_simulator?  I used the ardrone_testworld.launch file
2.  Which tum_simulator are you using?  I used the master branch from: https://github.com/kbogert/tum_simulator
3.  With the tum_simulator running, can you see the camera if you run: rosrun image_view image_view image:=/ardrone/image_raw

**Comment by pulver22** [comment]
1) Same as you

2) I'm using the simulator from the original project  ( https://github.com/tum-vision/tum_simulator )

3) Yes but... for another part of the project I'm working on I renamed /ardrone/image_raw in /camera/image_raw. So I can see the camera listening to this topic.

As said before, console does not report any error and only two windows that appear are the "uga_tum_ardrone GUI" and "PTAM Drone Map View".

**Comment by pulver22** [comment]
I confirm that reverting the changes I did to tum_simulator I can now see this window. Therefore I can close the issue!
